# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11075e3eea5078c638c7d9a4dacec66ddf18a34df8a261173494b5fe1de9b39e99cb36cf22a91f0f3bbb51efe7185f3b35f98cfe9729877df38570b4e4f3f0d9

test:
  secret_key_base: ea59f6d11a6084cfc5ee171452c5e110b520a881100aeb53dd566563c700ff69753efdfcb0683c12d8a6ec5ed492bd3534d5ddc54cf592ccf9f3d789128dd49c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
